<?php

namespace PackageVersions;

/**
 * This class is generated by muglug/package-versions, specifically by
 * @see \PackageVersions\Installer
 *
 * This file is overwritten at every run of `composer install` or `composer update`.
 */
final class Versions
{
    const VERSIONS = array (
  'composer/ca-bundle' => '1.0.9@36344aeffdc37711335563e6108cda86566432a6',
  'composer/composer' => '1.5.2@c639623fa2178b404ed4bab80f0d1263853fa4ae',
  'composer/semver' => '1.4.2@c7cb9a2095a074d131b65a8a0cd294479d785573',
  'composer/spdx-licenses' => '1.1.6@2603a0d7ddc00a015deb576fa5297ca43dee6b1c',
  'doctrine/instantiator' => '1.1.0@185b8868aa9bf7159f5f953ed5afb2d7fcdc3bda',
  'justinrainbow/json-schema' => '5.2.6@d283e11b6e14c6f4664cf080415c4341293e5bbd',
  'myclabs/deep-copy' => '1.7.0@3b8a3a99ba1f6a3952ac2747d989303cbd6b7a3e',
  'phpdocumentor/reflection-common' => '1.0.1@21bdeb5f65d7ebf9f43b1b25d404f87deab5bfb6',
  'phpdocumentor/reflection-docblock' => '4.1.1@2d3d238c433cf69caeb4842e97a3223a116f94b2',
  'phpdocumentor/type-resolver' => '0.4.0@9c977708995954784726e25d0cd1dddf4e65b0f7',
  'phpspec/prophecy' => 'v1.7.2@c9b8c6088acd19d769d4cc0ffa60a9fe34344bd6',
  'phpunit/php-code-coverage' => '4.0.8@ef7b2f56815df854e66ceaee8ebe9393ae36a40d',
  'phpunit/php-file-iterator' => '1.4.2@3cc8f69b3028d0f96a9078e6295d86e9bf019be5',
  'phpunit/php-text-template' => '1.2.1@31f8b717e51d9a2afca6c9f046f5d69fc27c8686',
  'phpunit/php-timer' => '1.0.9@3dcf38ca72b158baf0bc245e9184d3fdffa9c46f',
  'phpunit/php-token-stream' => '2.0.1@9a02332089ac48e704c70f6cefed30c224e3c0b0',
  'phpunit/phpunit' => '5.7.23@78532d5269d984660080d8e0f4c99c5c2ea65ffe',
  'phpunit/phpunit-mock-objects' => '3.4.4@a23b761686d50a560cc56233b9ecf49597cc9118',
  'psr/log' => '1.0.2@4ebe3a8bf773a19edfe0a84b6585ba3d401b724d',
  'sebastian/code-unit-reverse-lookup' => '1.0.1@4419fcdb5eabb9caa61a27c7a1db532a6b55dd18',
  'sebastian/comparator' => '1.2.4@2b7424b55f5047b47ac6e5ccb20b2aea4011d9be',
  'sebastian/diff' => '1.4.3@7f066a26a962dbe58ddea9f72a4e82874a3975a4',
  'sebastian/environment' => '2.0.0@5795ffe5dc5b02460c3e34222fee8cbe245d8fac',
  'sebastian/exporter' => '2.0.0@ce474bdd1a34744d7ac5d6aad3a46d48d9bac4c4',
  'sebastian/global-state' => '1.1.1@bc37d50fea7d017d3d340f230811c9f1d7280af4',
  'sebastian/object-enumerator' => '2.0.1@1311872ac850040a79c3c058bea3e22d0f09cbb7',
  'sebastian/recursion-context' => '2.0.0@2c3ba150cbec723aa057506e73a8d33bdb286c9a',
  'sebastian/resource-operations' => '1.0.0@ce990bb21759f94aeafd30209e8cfcdfa8bc3f52',
  'sebastian/version' => '2.0.1@99732be0ddb3361e16ad77b68ba41efc8e979019',
  'seld/cli-prompt' => '1.0.3@a19a7376a4689d4d94cab66ab4f3c816019ba8dd',
  'seld/jsonlint' => '1.6.1@50d63f2858d87c4738d5b76a7dcbb99fa8cf7c77',
  'seld/phar-utils' => '1.0.1@7009b5139491975ef6486545a39f3e6dad5ac30a',
  'symfony/console' => 'v3.3.12@099302cc53e57cbb7414fd9f3ace40e5e2767c0b',
  'symfony/debug' => 'v3.3.12@74557880e2846b5c84029faa96b834da37e29810',
  'symfony/filesystem' => 'v3.3.12@77db266766b54db3ee982fe51868328b887ce15c',
  'symfony/finder' => 'v3.3.12@138af5ec075d4b1d1bd19de08c38a34bb2d7d880',
  'symfony/polyfill-mbstring' => 'v1.6.0@2ec8b39c38cb16674bbf3fea2b6ce5bf117e1296',
  'symfony/process' => 'v3.3.12@a56a3989fb762d7b19a0cf8e7693ee99a6ffb78d',
  'symfony/yaml' => 'v3.3.12@0938408c4faa518d95230deabb5f595bf0de31b9',
  'webmozart/assert' => '1.2.0@2db61e59ff05fe5126d152bd0655c9ea113e550f',
  'muglug/package-versions' => '1.0.0.0@c37fd683a997552f30900f73f3f6945ffac3fc70',
);

    private function __construct()
    {
    }

    /**
     * @throws \OutOfBoundsException if a version cannot be located
     */
    public static function getVersion($packageName)
    {
        $selfVersion = self::VERSIONS;

        if (! isset($selfVersion[$packageName])) {
            throw new \OutOfBoundsException(
                'Required package "' . $packageName . '" is not installed: cannot detect its version'
            );
        }

        return $selfVersion[$packageName];
    }

    /**
     * @throws \OutOfBoundsException if a version cannot be located
     */
    public static function getShortVersion($packageName)
    {
        return explode('@', static::getVersion($packageName))[0];
    }

    /**
     * @throws \OutOfBoundsException if a version cannot be located
     */
    public static function getMajorVersion($packageName)
    {
        return explode('.', static::getShortVersion($packageName))[0];
    }
}
